# Generated by Django 5.2.13 on 2026-07-17 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeconfig',
            name='max_number_of_resumes',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
