# Generated by Django 5.2.13 on 2026-08-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_cgpa_student_tenth_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cgpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='tenth_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='twelfth_percentage',
        ),
        migrations.RemoveField(
            model_name='student',
            name='whatsapp_number',
        ),
    ]
