# Generated by Django 5.2.13 on 2026-07-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('not applied', 'Not Applied'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('placed', 'Placed')], default='applied', max_length=255),
        ),
    ]
