# Generated by Django 5.2.13 on 2026-07-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_alter_application_status'),
        ('student', '0003_alter_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Not Applied', 'Not Applied'), ('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Placed', 'Placed')], default='Applied', max_length=255),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('student', 'job'), name='unique_student_job'),
        ),
    ]
