# Generated by Django 5.2.13 on 2026-07-09 02:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_application_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='job_description',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='job_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='job_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='job_title',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='application',
            name='student_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='student_whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
