# Generated by Django 5.2.13 on 2026-07-09 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_application_job_description_application_job_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='student_email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
