# Generated by Django 5.2.13 on 2026-07-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_application_student_email_id'),
        ('student', '0003_alter_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('file_name', models.TextField()),
                ('file', models.FileField(upload_to='media/resumes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='student.student')),
            ],
        ),
    ]
