# Generated by Django 5.2.13 on 2026-07-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_name',
            field=models.TextField(default=''),
        ),
    ]
