# Generated by Django 5.2.13 on 2026-07-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='student_email_id',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
