# Generated by Django 5.2.13 on 2026-07-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_alter_resume_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='file_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
