# Generated by Django 5.2.13 on 2026-07-11 17:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_alter_resume_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, validators=[django.core.validators.MaxValueValidator(Decimal('20.00'))]),
        ),
    ]
