# Generated by Django 5.2.13 on 2026-08-06 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_resume_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('enum', 'Enum')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=100)),
                ('attribute_slug', models.SlugField()),
                ('data_type', models.CharField(max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('value', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='job.application')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JobAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=False)),
                ('visible_to_company', models.BooleanField(default=True)),
                ('filterable', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='job.attribute')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='job.job')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('job', 'attribute')},
            },
        ),
    ]
