# Generated by Django 5.2.13 on 2026-07-29 02:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_alter_resume_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume_file',
        ),
        migrations.AddField(
            model_name='application',
            name='resume_detail',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='resume',
            name='detail',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
