# Generated by Django 5.2.13 on 2026-07-29 02:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_application_resume_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
