# Generated by Django 5.2.13 on 2026-08-06 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_attribute_remove_application_resume_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='resume_file',
        )
    ]
