# Generated by Django 5.2.13 on 2026-08-09 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_auto_20260806_0425'),
        ('student', '0004_student_cgpa_student_tenth_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.JSONField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.attribute')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'attribute'), name='unique_student_attribute')],
            },
        ),
    ]
