# Generated by Django 5.2.13 on 2026-07-31 17:26

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_alter_resume_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume_detail',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
