# Generated by Django 5.2.13 on 2026-08-09 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_studentattributevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='student_phone_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student_whatsapp_number',
        ),
    ]
