# Generated by Django 5.2.13 on 2026-08-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0018_alter_resume_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationexport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media/exports/'),
        ),
    ]
