# Generated by Django 5.2.13 on 2026-09-06 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0019_alter_applicationexport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('phone_number', 'Phone Number')], max_length=20),
        ),
    ]
